name: LogicLane_chatbot
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py310haa95532_0
  - libffi=3.4.2=hd77b12b_6
  - openssl=1.1.1t=h2bbff1b_0
  - python=3.10.9=h966fe2a_0
  - setuptools=65.6.3=py310haa95532_0
  - sqlite=3.40.1=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022g=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.10=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.0
      - charset-normalizer==3.0.1
      - click==8.1.3
      - colorama==0.4.6
      - flatbuffers==23.1.21
      - gast==0.4.0
      - google-auth==2.16.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.3
      - h5py==3.8.0
      - idna==3.4
      - joblib==1.2.0
      - keras==2.11.0
      - libclang==15.0.6.1
      - markdown==3.4.1
      - markupsafe==2.1.2
      - nltk==3.8.1
      - numpy==1.24.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.0
      - pip==23.0.1
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - regex==2022.10.31
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.1
      - scipy==1.10.1
      - six==1.16.0
      - sklearn==0.0.post1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-intel==2.11.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tqdm==4.64.1
      - typing-extensions==4.5.0
      - urllib3==1.26.14
      - werkzeug==2.2.3
      - wrapt==1.14.1
prefix: C:\Users\Igor\anaconda3\envs\LogicLane_chatbot
